config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories, except: [:destroy]
  root "homes#landingPage"
  get '/about', to: 'homes#about'
  # root :to => redirect('/articles')
  resources :articles
  get 'signup', to: 'users#new'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'
  resources :users, except: [:new]
end

app/models/Article.rb
class Article < ApplicationRecord 
  belongs_to :user

  validates :title, 
            presence: true,
            length: {minimum:6,maximum:100}

  validates :description,
            presence: true,
            length: {minimum:10,maximum:500}
end

app/models/User.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy

  validates :username, presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum:3, maximum:25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: {case_sensitive: false},
            length: {maximum:105},
            format: {with: VALID_EMAIL_REGEX}
  
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord 

  validates :name, presence: true, uniqueness: true, length: {minimum:4,maximum:25}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user , :logged_in?
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end 

  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:index,:show]
  before_action :require_same_user, only: [:update,:edit,:destroy]

  def show
    
  end

  def index 
    @articles = Article.paginate(page:params[:page], per_page:5)
  end

  def new 
    @article = Article.new 
  end

  def create 
    @article = Article.new(articles_params)
    @article.user = current_user
    if (@article.save)
      flash[:notice] = "Article was created sucessfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit 
    
  end

  def update 
    
    if (@article.update(articles_params))
      flash[:notice] = "Article was updated sucessfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy 
    
    @article.destroy
    redirect_to articles_path
  end

  private
  def articles_params 
    params.require(:article).permit(:title,:description)
  end

  def  set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit your own articles"
      redirect_to articles_path
    end
  end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index 
  
  end

  def new 

  end 

  def show

  end 
  
end

app/controllers/homes_controller.rb
class HomesController  < ApplicationController

  def landingPage
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new 

  end

  def create 
      user = User.find_by(email:params[:session][:email].downcase)
      if(user && user.authenticate(params[:session][:password]))
        session[:user_id] = user.id
        flash[:notice] = "Logged in successfully"
        redirect_to user_path(user)
      else
        flash.now[:alert] = "There was an error with your credentials"
        render "new"
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update,:destroy]
  before_action :require_same_user, only:[:edit,:update,:destroy]

  def index 
    @users = User.paginate(page:params[:page], per_page:5)
  end

  def new 
    @user = User.new
  end

  def show
    @articles = @user.articles.paginate(page:params[:page], per_page:5)
  end 

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, #{@user.username}. You have successfuly loggin."
      redirect_to articles_path
    else
      render "new"
    end
  end

  def edit 
  end 

  def update
    if @user.update(user_params)
      flash[:notice] = "Yoour account information was successfully updated"
      redirect_to user_path(@user)
    else 
      render "edit"
    end 
  end 

  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user
    flash[:notice] = "Account and associated articles have been delete."
    redirect_to root_path
  end 

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
    @user =  User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own articles"
      redirect_to articles_path
    end
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
   
   def gravatar_for(user,options = {size:80})
      email = user.email.downcase 
      hash = Digest::MD5.hexdigest(email)
      size = options[:size] 
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url,alt: user.username,class:"rounded shadow mt-4 mx-auto d-block")
   end

   

end

app/views/articles/_article.html.erb
<% if @articles.any? %>
  <% @articles.each do |article|%>
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card m-3 shadow text-center">
          <div class="card-header font-italic">
            by <%= link_to  article.user.username, article.user  %> 
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%=truncate(article.description,length:100)%></p>
            <%= link_to  "View", article_path(article), class:"btn btn-outline-info m-1" %>
            <%if logged_in? && (article.user == current_user || current_user.admin?)%>
              <%= link_to  "Edit", edit_article_path(article),class:"btn btn-outline-success m-1" %>
              <%= link_to  "Delete", article_path(article),method: "delete",class:"btn btn-outline-danger m-1", data: {confirm: "Are you sure?"} %>
            <%end%>
          </div>
          <div class="card-footer">
            <small>Created <%=time_ago_in_words(article.created_at)%>, Updated <%=time_ago_in_words(article.updated_at)%>  </small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
<%else%>
  <h4 class="text-center mt-4">There are no articles yet, try creating one. </h4>
  <div class="text-center">
    <%= link_to  "New +", new_article_path, class: "btn btn-primary" %>
  </div>
<%end%>

app/views/articles/_form.html.erb
<div class="container">
  <%= render  "shared/form_errors", obj:@article %>
  <%=form_with model: @article,class:"shadow p-3 m-5 bg-dark text-white rounded", local: true  do |f|%>
    <div class="form-group row">
      <%=f.label :title, class:"col-md-2 col-sm-3 col-form-label"%>
      <div class="col-md-10 col-sm-9">
        <%= f.text_field :title, class:"form-control shadow"%>
      </div>
    </div>
    <div class="form-group row">
      <%=f.label :description,class:"col-md-2 col-sm-3 col-form-label"%>
        <div class="col-md-10 col-sm-9">
          <%= f.text_area :description, rows:10, class:"form-control shadow"%>
        </div>
    </div>
    <div class="form-group row justify-content-center">
      <%=f.submit class:"btn btn-outline-light btn-lg shadow"%>
    </div>
  <%end%>
  <div class="row justify-content-center mb-5">
    <%= link_to  "[ Cancel and Return to article listing ]", articles_path()  %>
  </div>
</div>

app/views/articles/_form_errors.html.erb
<% if @article.errors.any?%>
  <div class="alert alert-danger alert-dismissible fade show  ml-5 mr-5" role="alert">
    <h2>The following errors prevented your article from being processed:</h2>
    <ul>
      <%@article.errors.full_messages.each do |msg|%>
          <li><%=msg%></li>
      <%end%>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end%>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4"> Edit article</h1>
<%= render  "form" %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render  "article" %>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4"> Create new article</h1>
<%= render  "form" %>

app/views/articles/show.html.erb
<h5 class="text-center m-3"><%=@article.title%></h5>
<div class="container">
 <div class="row justify-content-center">
      <div class="col-10">
        <div class="card m-3 shadow text-center">
          <div class="card-body">
            <p class="card-text"><%=@article.description%></p>
            <%if logged_in? && (@article.user == current_user || current_user.admin?)%>
              <%= link_to  "Edit", edit_article_path(@article),class:"btn btn-outline-success m-1" %>
              <%= link_to  "Delete", article_path(@article),method: "delete",class:"btn btn-outline-danger m-1", data: {confirm: "Are you sure?"} %>
            <%end%>
          </div>
          <div class="card-footer">
            <small>Created <%=time_ago_in_words(@article.created_at)%>, Updated <%=time_ago_in_words(@article.updated_at)%>  </small>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/categories/index.html.erb
<h1>Index</h1>

app/views/categories/new.html.erb
<h1>New</h1>

app/views/categories/show.html.erb
<h1>Show</h1>

app/views/homes/landingPage.html.erb
<div class="container home-container">
  <div class="jumbotron text-center">
    <div class="jumbotron-custom">
      <h1 class="display-4">LET'S BLOG</h1>
      <p class="lead">When you have an idea and need to share it.</p>
      <hr class="my-4">
      <br/>
      <br/>
      <br/>
      <%= link_to  "Sign Up!", signup_path , class:"btn btn-success btn-lg m-5" %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
 <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to  "Gary Github", "https://github.com/Gary1690", class:"text-white" %></small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<%flash.each do |name,msg|%>
  <div class='alert <%= name === "alert" ? "alert-danger" : "alert-success"%> text-center'> 
    <%=msg%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
 <nav class="navbar  navbar-dark navbar-expand-lg">
    <%= link_to  "LET'S BLOG", root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to  "Bloggers", users_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%if logged_in?%>
              <%= link_to  "New Article", new_article_path, class:"dropdown-item" %>
            <%end%>
              <%= link_to  "Article Listing", articles_path, class:"dropdown-item" %>
          </div>
        </li>
        <%if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin?%> | <%= current_user.username%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to  "View profile", user_path(current_user), class:"dropdown-item" %>
              <%= link_to  "Edit Profile", edit_user_path(current_user), class:"dropdown-item" %>
              <%= link_to  "Delete Profile", user_path(current_user), class:"dropdown-item text-danger", method: :delete, data: {confirm:"Are you sure ?"} %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to  "Logout", logout_path, class:"nav-link", method: :delete %>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to  "Log in", login_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign up", signup_path, class:"nav-link" %>
          </li>
        <%end%>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LET'S BLOG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">  
   
    <%= render  "/layouts/navbar" %>
    <div id="page-content">
    <%= render  "/layouts/messages" %>
    <%= yield %>
    </div>
    <%= render  "/layouts/footer" %>
  </body>
</html>

app/views/session/new.html.erb
<h1 class="text-center mt-4"> Log in</h1>

<div class="container">
  <%=form_with( scope: :session, url: login_path, class:"shadow p-3 m-5 bg-dark text-white rounded", local: true)  do |f|%>
    <div class="form-group row">
      <%=f.label :email,class:"col-md-2 col-sm-3 col-form-label"%>
        <div class="col-md-10 col-sm-9">
          <%= f.email_field :email, class:"form-control shadow"%>
        </div>
    </div>
    <div class="form-group row">
      <%=f.label :password,class:"col-md-2 col-sm-3 col-form-label"%>
        <div class="col-md-10 col-sm-9">
          <%= f.password_field :password, class:"form-control shadow"%>
        </div>
    </div>
    <div class="form-group row justify-content-center">
      <%=f.submit "Log in", class:"btn btn-outline-light btn-lg shadow"%>
    </div>
  <%end%>
  <div class="row justify-content-center mb-5">
    <%= link_to  "[ Cancel and Return to article listing ]", articles_path()  %>
  </div>
</div>

app/views/shared/_form_errors.html.erb
<% if obj.errors.any?%>
  <div class="alert alert-danger alert-dismissible fade show  ml-5 mr-5" role="alert">
    <h2>The following errors prevented your <%=obj.class.name.downcase%> from being processed:</h2>
    <ul>
      <%obj.errors.full_messages.each do |msg|%>
          <li><%=msg%></li>
      <%end%>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end%>

app/views/users/_form.html.erb
<div class="container">
  <%= render  "shared/form_errors", obj:@user %>
  <%=form_with model:@user, class:"shadow p-3 m-5 bg-dark text-white rounded", local: true  do |f|%>
    <div class="form-group row">
      <%=f.label :username, class:"col-md-2 col-sm-3 col-form-label"%>
      <div class="col-md-10 col-sm-9">
        <%= f.text_field :username, class:"form-control shadow"%>
      </div>
    </div>
    <div class="form-group row">
      <%=f.label :email,class:"col-md-2 col-sm-3 col-form-label"%>
        <div class="col-md-10 col-sm-9">
          <%= f.email_field :email, class:"form-control shadow"%>
        </div>
    </div>
    <div class="form-group row">
      <%=f.label :password,class:"col-md-2 col-sm-3 col-form-label"%>
        <div class="col-md-10 col-sm-9">
          <%= f.password_field :password, class:"form-control shadow"%>
        </div>
    </div>
    <div class="form-group row justify-content-center">
      <%=f.submit (@user.new_record? ? "Sign Up": "Update Account"), class:"btn btn-outline-light btn-lg shadow"%>
    </div>
  <%end%>
  <div class="row justify-content-center mb-5">
    <%= link_to  "[ Cancel and Return to article listing ]", articles_path()  %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4"> Edit your profile </h1>
<%= render  "form" %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Bloggers</h1>
<div class="apple_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>


<div class="container">
 
  <%if @users.any?%>
    <%@users.each  do |user|%>
      <div class="card text-center m-5">
        <div class="card-header">
          <%=user.username%>
        </div>
        <div class="card-body">
            <%=gravatar_for user, size: 100%>
            <p class="text-center m-2"> <%=pluralize(user.articles.count, "article")%></p>
            <div class="text-center">
                <%= link_to  "View Profile", user_path(user), class:"btn btn-outline-success" %>
                <%if logged_in?%>
                    <%if current_user.admin?%>
                      <%= link_to  "Delete Profile", user_path(user), class:"btn btn-outline-danger",method: :delete, data:{confirm:"Are you sure?"} %>
                    <%end%>
                    <%if user == current_user%>
                      <%= link_to  "Edit Profile", edit_user_path(user), class:"btn btn-outline-primary" %>
                    <%end%>
                <%end%>
                
            </div>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%=time_ago_in_words(user.created_at)%></small>
        </div>
      </div>
    <%end%>
  <%else%>
    <h3 class="text-center mt-5">We need some bloggers</h3>
    <div class=text-center>
      <%= link_to  "Sign Up!", signup_path, class:"btn btn-outline-primary" %>
    </div>
  <%end%>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign Up for <b>Let's Blog!</b> </h1>
<%= render  "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%=@user.username%>'s profile </h1>
<%=gravatar_for @user,size: 200%>
<%if logged_in? && @user == current_user%>
  <div class="text-center mt-4">
    <%= link_to  "Edit Profile", edit_user_path(@user), class:"btn btn-outline-primary" %>
  </div>
<%end%>
<h3 class="text-center mt-4"> Articles </h3>
<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render  "articles/article" %>
<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>